#include <cstdio>
#include <cstdlib>

namespace {

const char out_name[] = "sincos.s";

const char preamble[] =
  "# sin + cos lookup table\n"
  "# generated by " __FILE__ "\n"
  "\n"
  ".file \"sincos.s\"\n"
  "\n"
  ".globl _maths_sin_lookup\n"
  ".globl _maths_cos_lookup\n"
  "\n"
  ".data\n" // TODO: gcc defaulted this to .text
  ".p2align 1\n"
  "_maths_sin_lookup:\n"
;

bool check_fpu() {
  volatile float a = 1.f;
  volatile float b = 2.f;
  if (a * b != b) return false;
  if (a + a != b) return false;
  return a > 0;
}

} // namespace

int main() {
  // Check we can actually use the FPU.
  if (!check_fpu()) {
    printf("FPU check failed\n");
    return EXIT_FAILURE;
  }

  // Open file.
  FILE * output = fopen(out_name, "w");
  if (!output) {
    printf("Failed to open %s\n", out_name);
    return EXIT_FAILURE;
  }

  // Write preamble.
  fprintf(output, preamble);

  // Extra quadrant for cos, which aliases with the sin array.
  const int quadrant_size = 256 / 4;
  for (int x = 0; x < quadrant_size * 5; x++) {
    // cos starts a quadrant in.
    if (x == quadrant_size) {
      fprintf(output, "_maths_cos_lookup:\n");
    }
    if ((x % quadrant_size) == 0) {
      fprintf(output, "# quadrant start\n");
    }

    // Calculate the sin.
    float f = sin(x * (2 * 3.14159f / 256));
    int i = static_cast<int>(127 * f);
    fprintf(output, ".byte %i\n", i);
  }

  // Done.
  printf("Lookups written to %s\n", out_name);
  fclose(output);
  return EXIT_SUCCESS;
}
