# Common flags
include ..\\libpc98\\flags.mk

# What we're building
DEPS	+= $(LIBPC98) game.h loading.h menus.h pal_fade.h
OBJS	= main.o loading.o mn_main.o mn_splsh.o pal_fade.o mn_lvls.o
TARGET	= aaa.exe

# Build it
include ..\\libpc98\\exe.mk
